spring.application.name=TinyURL

server.port=8081

app.base-url=http://localhost:8080

# MySQL (Aiven)

spring.datasource.url=jdbc:mysql://tinyurl-mysql-tinyurl.l.aivencloud.com:28376/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WOUVlv46EL2byTl6SGa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
