spring.application.name=TinyURL

app.base-url=http://localhost:8080

#MySQL configuration
# college/hospitalDB/urlshortener is a database name
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener

# We are not hardcoding the username and password here. Instead, we use placeholders
# that will be resolved from environment variables (e.g., set by Docker Compose).
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=root
spring.datasource.password=@Fenilsavaliya23

#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update

#SQL query will show in logs
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
#Query will remain in SQL format

server.error.include-message=always
server.error.include-binding-errors=always

jwt.secret=YourVeryLongSecretKeyForTinyUrlProject2026SpringBootReactJWTAuthentication
jwt.expiration=86400000
  #86400000 ms mean 24 hours
